version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user


hooks:
  ApplicationStop:
    - location: stop-process.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 180
      runas: ec2-user
