version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - python -m pip install awscliv2
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
    
artifacts:
    files:
        - "/root/.m2/repository/org/springframework/demo2/**/*"
        
